### ISSUE TITLE
Very strange behavior, looped update, v 0.2.8

### ISSUE THREAD

**Issue by avevlad** [rlivings39/vscode-fzf-quick-open#12]
log:
>   ERR Manifest is not found rlivings39.fzf-quick-open

Video:

[Screen Recording 2020-05-21 .mov.zip](https://github.com/rlivings39/vscode-fzf-quick-open/files/4664720/Screen.Recording.2020-05-21.mov.zip)

![image](https://user-images.githubusercontent.com/2889662/82606629-106fa600-9bc0-11ea-8ca3-7235567f1954.png)

**Comment by rlivings39** [comment]
If you try again with 0.2.9 does that resolve the issue? There were publishing errors with 0.2.8 because I was inadvertently packaging unwanted files.

**Comment by avevlad** [comment]
@rlivings39 work! Thanks!
