### ISSUE TITLE
Add case-insensitive search for the word under cursor

### ISSUE THREAD

**Issue by vaibhav1618** [rlivings39/vscode-fzf-quick-open#13]
It's a feature request. Please add case-insensitive search for the word under the cursor

**Comment by rlivings39** [comment]
Are you looking for search with rg or another search?

**Comment by vaibhav1618** [comment]
With Rg. It's actually two separate requests: one is to have configurable option for case-insensitive search (or smart-search) by default. Other is search for the word under cursor.

**Comment by rlivings39** [comment]
Thanks for the clarification. (2) should be handled in my submission yesterday. That's in 0.2.10 that I published yesterday. Let me know what that's missing.

The built in ctrl+sfift+f in vscode also initializes the search with the word under the cursor.

**Comment by vaibhav1618** [comment]
Thanks, it works well. Found one behavior that can possibly change:
1. Search for a keyword. Results would appear on the terminal
2. Without making a selection, search for another keyword. This search fails.

> The built in ctrl+sfift+f in vscode also initializes the search with the word under the cursor.

It's not fuzzy :)

**Comment by rlivings39** [comment]
I split out #16 for that issue

**Comment by rlivings39** [comment]
Added an `rg` case setting and published in v0.2.12
