### ISSUE TITLE
Finding the extension on vscode

### ISSUE THREAD

**Issue by vaibhav1618** [rlivings39/vscode-fzf-quick-open#14]
Thanks for the extension. Have couple of suggestions to make it easier to find the extension on vscode:
1. Add `fuzzy` in title/tags/description.
2. Highlight `search` more. This extension stands out for fuzzy keyword search. Native support for fuzzy file search is quite OK on vscode.

**Comment by rlivings39** [comment]
Thank you for the suggestion. I took a crack at this in v0.2.11. Let me know if you see any other opportunities to improve the listing. The extension now shows if I search the extension store for fuzzy, fzf, and ripgrep

**Comment by rlivings39** [comment]
Closing based on improvements made
