### ISSUE TITLE
Maybe there is no need to "escapeWinPath"

### ISSUE THREAD

**Issue by DaddyTrap** [rlivings39/vscode-fzf-quick-open#23]
I'm working on Windows. I found that using `fzf: Open file using fzf` the fzf runs well but when I selected the file, vscode dosen't open the file. Also, I got a error message said "The specified path is invalid." on cmd.

After reading the code, I tried the following operations on cmd:
```
C:\Users\my_username>echo open $$ F:\Path\To\Workspace $$ server\bin\start.bat > "\\?\pipe\fzf-pipe-21160"

C:\Users\my_username>echo open $$ F:\\Path\\To\\Workspace $$ server\bin\start.bat > "\\?\pipe\fzf-pipe-21160"

C:\Users\my_username>echo open $$ F:\\Path\\To\\Workspace $$ server\bin\start.bat > "\\\\?\\pipe\\fzf-pipe-21160"
The specified path is invalid.

C:\Users\my_username>
```
It shows that, the first 2 command did work and my vscode opened that `start.bat`, however, the 3rd one echos an error. But now 
what the extension produces is like the 3rd one.

I tried modifying `function escapeWinPath` to make it just `return origPath;`, and it seems everything works well.

Is it truly necessary to use `escapeWinPath` on the named pipe and the path to `scripts\topipe.bat` ?

---

PS: I think this extension will really save my time! 😆 vscode's `Ctrl+P` can be very slow when I'm working on a large project.

**Comment by sim590** [comment]
I am getting `The specified path is invalid` also after a fresh install of the FZF plugin on a fresh install of VSCode.

I tried to comment out the content of my Powershell profile file and it didn't change anything. The plugin seems to open my Pwsh shell (powershell 7).
