### ISSUE TITLE
Add RipGrep options

### ISSUE THREAD

**Issue by janosimas** [rlivings39/vscode-fzf-quick-open#29]
Hi, just started using and it's a great extension.

I miss being able to set ripgrep options. I have some generated files that are ignored by the default config and it would be nice to be able to set ripgrep flags to not ignore them.

**Comment by rlivings39** [comment]
Hey thanks! This would be easy to add. I could imagine a few ways:

* Have a config setting. This would be good if your options don't change much.
* Prompt every time you call rg and remember the last used options

The first is simpler to implement and less noisy during the workflow so I'd likely go with that. Thoughts?

**Comment by janosimas** [comment]
I think the first option is better in any case.
Vscode already allows to have a general and a per workspace config, ti should cover most of the cases.

Another option would be a sidebar, like built in search.
I like this idea but this would be a huge change and I assume a lot of work.
