### ISSUE TITLE
Implement file content search

### ISSUE THREAD

**Issue by BuZZ-dEE** [rlivings39/vscode-fzf-quick-open#6]
Hi, thx for this great plugin, [I really like it](https://github.com/headmelted/codebuilds/issues/113).

Could you please also implement file content search?

**Comment by rlivings39** [comment]
Seems doable. A few questions come to mind:

* What would this do that the VSCode integrated search would do?

* Do you have an fzf-based command in mind for doing the searching? What would the action be when you choose a search result? (open the associated file at the location?) I'm curious what you'd imagine the workflow to be

**Comment by BuZZ-dEE** [comment]
> What would this do that the VSCode integrated search would do?
What do you mean? In My case I need this as a workaround for this [bug](https://github.com/headmelted/codebuilds/issues/113).  But I think it is good to have alternatives. ;)

> Do you have an fzf-based command in mind for doing the searching?
Yes

> What would the action be when you choose a search result? (open the associated file at the location?)
Just open the file in VSCode.

**Comment by rlivings39** [comment]
Thanks for the feedback. Any specific fzf command you'd want to run? Or should I try to cook something up? My bias would be to try and use ripgrep with fzf

**Comment by BuZZ-dEE** [comment]
Yes, try to cook something using `ripgrep`. I already [tried it and failed](https://stackoverflow.com/questions/61740910/how-do-i-fuzzy-find-all-files-containing-specific-text-using-ripgrep-and-fzf-and). ;)
